# Generated by Django 2.1 on 2019-05-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='admin', max_length=50, verbose_name='Username')),
                ('senha', models.CharField(default='123', max_length=50, verbose_name='Senha')),
                ('email', models.CharField(default='admin@turbonews.com', max_length=100, verbose_name='Email')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
    ]
