# Generated by Django 2.1 on 2019-06-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='ano',
            field=models.IntegerField(null=True, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='numVendas',
            field=models.IntegerField(null=True, verbose_name='numVendas'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='precoFipe',
            field=models.FloatField(null=True, verbose_name='PrecoFipe'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='segmento',
            field=models.CharField(max_length=50, null=True, verbose_name='Segmento'),
        ),
    ]
