# Generated by Django 2.1 on 2019-06-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190603_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opiniao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCarro', models.IntegerField(verbose_name='idCarro')),
                ('opiniao', models.TextField(verbose_name='Titulo')),
                ('estilo', models.IntegerField(verbose_name='Estilo')),
                ('acabamento', models.IntegerField(verbose_name='Acabamento')),
                ('interior', models.IntegerField(verbose_name='Interior')),
                ('desempenho', models.IntegerField(verbose_name='Desempenho')),
                ('consumo', models.IntegerField(verbose_name='Consumo')),
                ('geral', models.IntegerField(verbose_name='Geral')),
            ],
        ),
    ]
