# Generated by Django 2.1 on 2019-06-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_opiniao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opiniao',
            name='opiniao',
            field=models.TextField(verbose_name='Opiniao'),
        ),
    ]
