# Generated by Django 2.1 on 2019-06-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190607_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opiniao',
            name='consumo',
        ),
        migrations.RemoveField(
            model_name='opiniao',
            name='desempenho',
        ),
        migrations.RemoveField(
            model_name='opiniao',
            name='interior',
        ),
        migrations.RemoveField(
            model_name='opiniao',
            name='opiniao',
        ),
        migrations.AddField(
            model_name='opiniao',
            name='contras',
            field=models.TextField(default='pau', verbose_name='Contras'),
        ),
        migrations.AddField(
            model_name='opiniao',
            name='pros',
            field=models.TextField(default='pau', verbose_name='Pros'),
        ),
        migrations.AddField(
            model_name='opiniao',
            name='titulo',
            field=models.TextField(default='pau', verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='opiniao',
            name='geral',
            field=models.TextField(default='pau', verbose_name='Geral'),
        ),
        migrations.AlterField(
            model_name='opiniao',
            name='idCarro',
            field=models.IntegerField(default='pau', verbose_name='idCarro'),
        ),
    ]
