# Generated by Django 2.1 on 2019-06-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190607_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='precoFipe',
        ),
        migrations.AddField(
            model_name='carro',
            name='precoFipeFev',
            field=models.FloatField(blank=True, null=True, verbose_name='PrecoFipeFev'),
        ),
        migrations.AddField(
            model_name='carro',
            name='precoFipeMar',
            field=models.FloatField(blank=True, null=True, verbose_name='PrecoFipeMar'),
        ),
    ]
