# Generated by Django 2.1 on 2019-06-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190607_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='precoFipeAbr',
            field=models.FloatField(blank=True, null=True, verbose_name='precoFipeAbr'),
        ),
        migrations.AddField(
            model_name='carro',
            name='precoFipeJun',
            field=models.FloatField(blank=True, null=True, verbose_name='precoFipeJun'),
        ),
        migrations.AddField(
            model_name='carro',
            name='precoFipeMai',
            field=models.FloatField(blank=True, null=True, verbose_name='precoFipeMai'),
        ),
    ]
