# Generated by Django 2.1 on 2019-06-08 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190608_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opiniao',
            name='idCarro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Carro'),
        ),
    ]
