# Generated by Django 2.1 on 2019-06-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_carro_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
