# Generated by Django 2.1 on 2019-06-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190610_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
