# Generated by Django 2.1 on 2019-06-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190610_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='noticia',
            field=models.IntegerField(default=0, verbose_name='Noticia'),
        ),
    ]
